server.port=${ACADEMIC_SERVICE_PORT:8081}
spring.application.name=academic-service

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ups_gerencia}
spring.datasource.username=${DATABASE_USER:ups_user}
spring.datasource.password=${DATABASE_PASSWORD:ups_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true
